INSERT INTO restaurants (name, img, food_type, city, state, description) VALUES
    ('Phomiliar', '../images/pho1.jpg', 'Vietnamese', 'Austin', 'TX', 'Award winning food and Pho soup are sure to satisfy all of the Pho-natics and first-timers alike. Don&#39;t take our word for it... Stop by one of their two locations!'),
    ('Mucha Muchacha&#39;s', '../images/mexican.jpg', 'Mexican', 'Phoenix', 'AZ','Known for wacky creations. You could also order breakfast tacos stuffed with eggs, mashed potatoes and avocado.'),
    ('Green Bridge', '../images/steak.jpg', 'American', 'Decatur', 'NE', 'The Green Bridge is a local landmark. Established in 1956 which burnt down in 1998 and Rebuilt by a group of investors to open in 1999. Come on in for some popcorn shrimp and a Shirley Temple!'),
    ('Dundee&#39;s', '../images/pub.jpg', 'Pub', 'Charlotte', 'SC', 'World famous Fish n Chips, Reuben sandwich, and Single Malt Scotch Wall! Bring family & friends for some good food, an array of beverages, and quirky people.'),
    ('Greenhouse', '../images/salad.jpg', 'Vegetarian', 'Portland', 'OR', 'A Portland favorite for vegan comfort food since 1998! Be sure to try the sweet potato fries with banana ketchup!'),
    ('Low Country', '../images/boil.jpg', 'Cajun', 'Jackson', 'MS', 'Always seasoned just right, the crawfish is always fresh.  Ask for a side of butter, obviously.');


INSERT INTO ratings (restaurant_id, user_name, rating, review, review_date) VALUES
    (1, 'Xander_Swift', 5, 'I love cheese, especially caerphilly taleggio. Who moved my cheese bocconcini st. agur blue cheese cheeseburger croque monsieur macaroni cheese fromage edam. Manchego cheese strings stilton pecorino cottage cheese taleggio say cheese cheese slices. Paneer mozzarella blue castello stinking bishop brie st. agur blue cheese cream cheese cheese strings. Melted cheese mascarpone croque monsieur rubber cheese hard cheese roquefort cheese and biscuits smelly cheese. Hard cheese blue castello brie say cheese halloumi taleggio emmental cheese and wine. The big cheese cut the cheese ricotta.', 'July 20, 2014'),
    (1, 'Kaia95', 5, 'I love cheese, especially lancashire st. agur blue cheese. Pecorino jarlsberg cow rubber cheese cheddar stinking bishop fromage who moved my cheese. Cheese and wine brie cheese and wine stinking bishop halloumi edam stilton smelly cheese. Ricotta fromage smelly cheese bocconcini macaroni cheese cheese on toast cheese on toast rubber cheese. Everyone loves fromage brie pecorino queso cheesecake melted cheese camembert de normandie. Stinking bishop dolcelatte cheese on toast say cheese.', 'January 23, 2015'),
    (2, 'Coy_Fay59', 4, 'I love cheese, especially cheesy feet cheesy feet. Smelly cheese cheeseburger chalk and cheese mascarpone the big cheese say cheese pepper jack emmental. Squirty cheese manchego edam bocconcini cheddar pecorino monterey jack red leicester. Croque monsieur when the cheese comes out everybody is happy stinking bishop cheese on toast cheese and biscuits fromage blue castello gouda. Fromage swiss babybel halloumi airedale smelly cheese swiss macaroni cheese. Cow rubber cheese cheese slices cheeseburger danish fontina cow.', 'May 5, 2013'),
    (2, 'Alize74', 1, 'No speeches. Short speech. You lost your partner today. What is his name - Emilio? Emilio is going to prison. The DEA took all your money, your lab. You got nothing. Square one. But you know the business and I know the chemistry. I am thinking... maybe you and I could partner up. I am sorry, what were you asking me? Oh, yes, that stupid plastic container I asked you to buy. You see, hydrofluoric acid will not eat through plastic. It will, however, dissolve me', 'March 30, 2015'),
    (3, 'Naomie4', 4, 'I love cheese, especially pecorino say cheese. Lancashire gouda gouda squirty cheese red leicester cheese slices cheeseburger fromage frais. Goat red leicester cheese on toast dolcelatte mozzarella pecorino cheese slices the big cheese. Goat say cheese cream cheese cheddar cheese strings cottage cheese hard cheese lancashire. Taleggio halloumi queso roquefort the big cheese lancashire cheeseburger chalk and cheese. Pepper jack babybel cheese slices jarlsberg manchego monterey jack cream cheese airedale. Cheese slices fromage frais.', 'April 28, 2015'),
    (3, 'Hodor', 3, 'Hodor! Hodor hodor, hodor hodor, hodor, hodor hodor. Hodor hodor HODOR! Hodor hodor... Hodor hodor hodor? Hodor hodor - hodor... Hodor hodor hodor... Hodor hodor hodor?! Hodor, hodor. Hodor. Hodor, hodor - hodor, hodor, hodor hodor. Hodor, hodor. Hodor. Hodor, hodor hodor; hodor hodor; hodor hodor?! Hodor hodor; hodor hodor hodor! Hodor, HODOR hodor, hodor hodor hodor hodor; hodor hodor?! Hodor, hodor. Hodor. Hodor, hodor hodor hodor, hodor, hodor hodor.', 'December 18, 2014'),
    (4, 'Ramiro_Nader86', 1, 'I am a comfortador also. Last month he is the freak with jicama breath who waxes his back. No need, little lady, your tears of gratitude are enough for me. Welcome to the future, where cars fly, robots serve our every whim, and genetically engineered dinosaurs rule the Earth. I do not buckle. Occasionally I swashbuckle. Looking in windows, knocking on doors. I do not think Buffy is going to be too broken up over a pylon.', 'October 14, 2015'),
    (4, 'Marcelino_Pagac', 3, 'I love cheese, especially halloumi stinking bishop. Babybel pecorino melted cheese cheese slices jarlsberg cheese triangles bavarian bergkase babybel. Airedale roquefort manchego melted cheese camembert de normandie mascarpone parmesan parmesan. Cheese and biscuits taleggio goat bocconcini cut the cheese queso swiss stinking bishop. Fromage fromage frais port-salut edam cheese on toast cheese and biscuits pepper jack squirty cheese. Cauliflower cheese ricotta parmesan bavarian bergkase cheese and wine cheesecake cheddar blue castello. Danish fontina bavarian bergkase stinking bishop danish fontina cheese and biscuits port-salut say cheese.', 'June 21, 2014'),
    (5, 'Scotty_Cronin93', 1, 'No speeches. Short speech. You lost your partner today. What is his name - Emilio? Emilio is going to prison. The DEA took all your money, your lab. You got nothing. Square one. But you know the business and I know the chemistry. I am thinking... maybe you and I could partner up. I am sorry, what were you asking me? Oh, yes, that stupid plastic container I asked you to buy. You see, hydrofluoric acid will not eat through plastic. It will, however, dissolve me', 'June 3, 2015'),
    (5, 'Bryana_Weimann', 5, 'I love cheese, especially lancashire st. agur blue cheese. Pecorino jarlsberg cow rubber cheese cheddar stinking bishop fromage who moved my cheese. Cheese and wine brie cheese and wine stinking bishop halloumi edam stilton smelly cheese. Ricotta fromage smelly cheese bocconcini macaroni cheese cheese on toast cheese on toast rubber cheese. Everyone loves fromage brie pecorino queso cheesecake melted cheese camembert de normandie. Stinking bishop dolcelatte cheese on toast say cheese.', 'October 29, 2014'),
    (6, 'Edwin.Schinner6', 3, 'I am a comfortador also. Last month he is the freak with jicama breath who waxes his back. No need, little lady, your tears of gratitude are enough for me. Welcome to the future, where cars fly, robots serve our every whim, and genetically engineered dinosaurs rule the Earth. I do not buckle. Occasionally I swashbuckle. Looking in windows, knocking on doors. I do not think Buffy is going to be too broken up over a pylon.', 'February 15, 2016'),
    (6, 'Erin31', 4, 'I love cheese, especially halloumi stinking bishop. Babybel pecorino melted cheese cheese slices jarlsberg cheese triangles bavarian bergkase babybel. Airedale roquefort manchego melted cheese camembert de normandie mascarpone parmesan parmesan. Cheese and biscuits taleggio goat bocconcini cut the cheese queso swiss stinking bishop. Fromage fromage frais port-salut edam cheese on toast cheese and biscuits pepper jack squirty cheese. Cauliflower cheese ricotta parmesan bavarian bergkase cheese and wine cheesecake cheddar blue castello. Danish fontina bavarian bergkase stinking bishop danish fontina cheese and biscuits port-salut say cheese.', 'March 25, 2014');